// Module included in the following assemblies:
//
// * installing/installing_openstack/installing-openstack-installer-kuryr.adoc

[id="installation-osp-kuryr-known-limitations_{context}"]
= Known limitations of installing with Kuryr

There are known limitations when using Kuryr SDN, depending on the
{rh-openstack} version:

* An Amphora load balancer VM is deployed per OpenShift Service with
the default Octavia load balancer driver (Amphora driver). In a
resource-constrained environment, creating too many Services can cause
problems.

* Octavia {rh-openstack} version 13 does not support UDP listeners. Therefore,
OpenShift UDP services are not supported. UDP listeners are supported in
Octavia {rh-openstack} version 16 and later.

* Octavia {rh-openstack} version 13 cannot listen to multiple protocols on the
same port. Services that expose the same port to different protocols, like TCP
and UDP, are not supported. Listeners that use different protocols
are supported in {rh-openstack} version 16 and later.

[NOTE]
Only the Octavia Amphora driver supports different protocols on the same port
in {rh-openstack} version 16. The OVN Octavia driver does not support listeners
that use different protocols.

* Due to the above UDP limitations of Octavia, Kuryr forces Pods to use TCP
for DNS resolution in {rh-openstack} version 15 or earlier, or if OVN Octavia
driver is used. This is achieved with the `use-vc` option in `resolv.conf`.
This may be a problem for Go applications compiled without CGO support (i.e.
`CGO_ENABLED=0`) as the native Go resolver is using UDP only and is not
considering the `use-vc` option added by kuryr to the `resolv.conf` on `GO`
versions 1.12 or earlier. Additionaly, musl-based containers, including those
based on alpine, do not support the use-vc option.
